### ISSUE TITLE
Does not work with Cordova 8

### ISSUE THREAD

**Issue by welkensoyo** [ReallySmallSoftware/cordova-plugin-firebaseui-auth#1]
The scripts location is moved in Cordova 8 and this install breaks.

**Comment by ReallySmallSoftware** [comment]
I'm sorry to hear you are having issues. Could you please supply the following information:

- version of plugin being used
- framework (eg plain cordova, phonegap, etc)
- operating system you are using for dev

**Comment by ReallySmallSoftware** [comment]
Have released a new version to hopefully fix this. Closing as original poster has not responded.

**Comment by larssn** [comment]
Hello, we've seen a few issues in a fresh Cordova 8 project:

1. `cordova run/build android` doesn't work until you modify the gradle files to use gradle-wrapper 4.4.
2. It generally seems to work in the browser, but you have to call `signIn()` twice. First to cause the redirect where you select your login provider, which then redirects you back to the app. At this point you are still not logged in until you call `signIn()` again.
3. After doing `1.` nothing we do in android seems to work. We can verify that the initialisation process happens, and that we have an auth instance we can call `signIn()` on, but doing so does nothing. We've also hooked up the events, and they don't fire either (they work fine in the browser).

We're pretty determined to get away from the official JS SDK due to IndexedDB (as I mentioned in the other repo), so we investigating how to make this work. Any insights would be appreciated!

**EDIT**: There's an error in Android, I'm told, which is why it doesn't work. Here it is:
`java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.auth.FirebaseUser com.google.firebase.auth.FirebaseAuth.getCurrentUser()' on a null object reference` in FirebaseUIAuthPlugin at line 151.

**EDIT2**: Another error, which could be why the first one happens in the first place:
`java.lang.IllegalStateException: Check your google-services plugin configuration, the default_web_client_id string wasn't populated.`

`default_web_client_id` is not an existing field in a newly downloaded `google-services.json` file.

**EDIT3**: Seems related to a missing dependency on `com.google.gms.google-services`

**Comment by ReallySmallSoftware** [comment]
@larssn Have you looked at the history of the latest version? I think this covers some of the issues you are seeing:

WARNING: The Android update may require you to update com.google.gms:google-services to 4.0.0, com.android.tools.build:gradle to 3.1.2 and gradle to 4.4.4 (look in platforms/android/cordova/lib/builders/GradleBuilder.js)

Can't promise it coves them all!
