### ISSUE TITLE
How to know android firebase version?

### ISSUE THREAD

**Issue by mesqueeb** [ReallySmallSoftware/cordova-plugin-firebaseui-auth#6]
From readme we need:
```
ANDROID_FIREBASE_CORE_VERSION: the version of Firebase Core to use
ANDROID_FIREBASE_AUTH_VERSION: the version of Firebase Authentication to use
```
But I only ever worked with npm modules of Firebase & Firebaseui. How can I know what android version I must use?

**Comment by ReallySmallSoftware** [comment]
Hi. To start with you can try not specifying these - they will default to what should be suitable versions. The option is there because Google change the version number so often.

This [link](https://firebase.google.com/docs/android/setup#available_libraries) shows the latest versions.

Note that this is prefixed with ANDROID because it refers to using the plugin on Android, not the version of Android on which it is being used.

**Comment by mesqueeb** [comment]
Thanks so much for your insights!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
